# Generated by Django 4.2 on 2023-04-28 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0003_alter_usuario_nome'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='cpf',
            new_name='password',
        ),
    ]
